const nombre = prompt ("cual es tu nombre")
console.log(nombre)
console.log(typeof nombre)
const edad = prompt ("cual es tu edad")
console.log(typeof nombre)
const edad2 = parseInt (prompt ("cual es tu edad"))
console.log (typeof edad2)
